In [1]:
import math
import random
from collections import defaultdict
from pprint import pprint

In [2]:
# Prevent future/deprecation warnings from showing in output
import warnings
warnings.filterwarnings(action='ignore')

In [3]:
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import string
import nltk

In [4]:
from sklearn import *

In [5]:
sns.set_style(style='white')
sns.set_context(context='notebook', font_scale=1.3, rc={'figure.figsize': (16,9)})

In [6]:
with open('sakaja.txt') as f:
    contents = f.read()
    f.close()

In [7]:
#define special characters list
special_characters = ['!','#','$','%', '&','@','[',']',']','_','\n']

# lambda and join function
contents = ''.join(filter(lambda i:i not in special_characters, contents))
    

In [8]:
from nltk.tokenize import word_tokenize


In [9]:
data = word_tokenize(contents.lower())

In [10]:
from nltk.corpus import stopwords

In [11]:
english_stopwords = stopwords.words('english')
t_data = [t for t in data if t not in english_stopwords]

In [12]:
from nltk import PorterStemmer

In [13]:
ps = PorterStemmer()
token_data = [ps.stem(i) for i in t_data]

In [14]:
token_text = ' '.join([str(item) for item in token_data])

In [15]:
token_text

"ndubi moturi “ mimi ni johnson sakaja , togeth sakaja . kuna kitu tunataka kutaja . keep plug like charger . corona come larger nic , cba merger…. ” viral video releas covid-19 pandem , nairobi senat johnson sakaja excit social media creativ rap video featur two sons.although appear gotten lyric right , ’ one thing 37-year-old '' 'super-sen '' quit master ; watch mouth.hi recent struggl fight disqualif nairobi gubernatori race cast shadow man alway eat words.not even ‘ manag degre ’ team univers uganda would help learn care manag utter public . month releas rap hit , sakaja arrest break rule encourag peopl break.but sakaja one bow easili , vehement deni claim arrest ladi loung kilimani violat govern direct covid19. “ never arrest . ’ . show ob number , ” tweet hour later.aft pressur mount , mr sakaja would step chair senat ad hoc committe covid-19 pandem apologis mislead kenyans.in speech , would acknowledg inde broken rule expect guard. “ charact . outsid nine , would one thing . tak

In [16]:
from sklearn.feature_extraction.text import CountVectorizer

In [ ]:
corpus = [
    'This is the first document.',
    'This document is the second document.',
    'And this is the third one.',
    'Is this the first document?',
]
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(corpus)
vectorizer.get_feature_names_out()


print(X.toarray())

In [17]:
corpus = [token_text]
vect = CountVectorizer(max_features=2000)
X = vect.fit_transform(corpus)

In [18]:
print(X.toarray())

[[2 3 1 1 1 1 1 1 1 1 3 2 2 1 1 4 1 2 1 1 1 2 3 1 1 1 1 1 1 1 1 2 1 1 2 2
  1 1 1 1 1 1 1 2 1 3 1 1 2 1 3 1 1 1 1 1 1 3 1 1 1 1 1 1 3 1 2 1 1 1 1 1
  1 2 2 2 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 1 1 1 1 1 1 1 1 1 2 2 1 1 1
  1 1 1 2 3 1 1 3 1 1 2 1 1 2 1 1 1 1 1 1 1 1 1 1 1 2 1 1 1 1 1 2 1 1 1 1
  1 1 1 1 3 1 2 1 1 1 1 1 1 1 1 1 1 1 3 1 7 1 1 1 1 3 1 1 1 1 1 1 1 1 1 2
  5 1 1 1 1 2 1 2 1 4 1 1 1 1 2 1 1 1 1 2 1 1 1 1 2 1 1 2 1 1 2 1 2 1 1 1
  2 1 1 1 3 4 7 1 2 3 3 1 5 1 1 1 2 1 2 1 1 1 1 1 1 2 3 1 1 1 1 1 2 1 2 1
  1 3 3 1 2 1 1 1 1 1 1 2 1 6 2 2 2 1 2 1 1 1 1 1 1 1 1 1 1 1 2 6 1 4 1]]


In [19]:
import pickle

In [20]:
f = open('my_classifier.pickle', 'rb')

nb = pickle.load(f)

f.close()

In [21]:
nb.class_count_

array([84., 84.])

In [22]:
nb.feature_count_

array([[1., 2., 1., ..., 1., 0., 0.],
       [0., 2., 0., ..., 0., 1., 1.]])

In [23]:
nb.class_log_prior_

array([-0.69314718, -0.69314718])

In [24]:
nb.classes_

array([0, 1], dtype=int64)

In [25]:
nb.n_features_in_

7619

In [26]:
nb.get_params(deep=True)

{'alpha': 1.0, 'class_prior': None, 'fit_prior': True}

In [27]:
nb.class_log_prior_

array([-0.69314718, -0.69314718])

In [29]:
nb(X)

TypeError: 'MultinomialNB' object is not callable

In [38]:
print(X)

  (0, 167)	1
  (0, 158)	1
  (0, 153)	1
  (0, 170)	1
  (0, 118)	2
  (0, 222)	7
  (0, 255)	1
  (0, 128)	1
  (0, 126)	1
  (0, 260)	1
  (0, 129)	1
  (0, 120)	1
  (0, 193)	1
  (0, 139)	2
  (0, 42)	1
  (0, 53)	1
  (0, 48)	2
  (0, 131)	1
  (0, 171)	1
  (0, 38)	1
  (0, 152)	1
  (0, 272)	1
  (0, 270)	2
  (0, 210)	2
  (0, 57)	3
  :	:
  (0, 127)	1
  (0, 250)	2
  (0, 279)	1
  (0, 109)	1
  (0, 91)	1
  (0, 184)	1
  (0, 258)	1
  (0, 217)	1
  (0, 98)	1
  (0, 213)	1
  (0, 116)	1
  (0, 146)	1
  (0, 244)	1
  (0, 70)	1
  (0, 123)	1
  (0, 51)	1
  (0, 110)	1
  (0, 27)	1
  (0, 192)	1
  (0, 68)	1
  (0, 211)	1
  (0, 186)	1
  (0, 259)	1
  (0, 95)	1
  (0, 3)	1


In [31]:
Z = X.reshape(-1,1)

In [33]:
nb.predict(X)

ValueError: X has 287 features, but MultinomialNB is expecting 7619 features as input.